#!/bin/python3
import python_api_shared_data
""" python_api_shared_data module is a moudle generated by pybind11
    allowing an access to the main projects data.
    the get_vals function is getting the values produced by the main program
    by retrieving the data from boost::interprocess::managed_shared_memory.
    function location is at https://github.com/talvezu/ForMontee/tree/master/app/utils/DB.cpp
    module generated at build/app/utils, full name
    api_for_getting_system_data.cpython-310-x86_64-linux-gnu.so

"""
#print (dir(python_api_shared_data))
#print (dir(python_api_shared_data.main_db))
#print (dir(python_api_shared_data.main_db.get_vals))

data = python_api_shared_data.main_db.get_vals("db_shared_memory")
print(data)
