name: MacOS CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install GTK
      run: brew install gtk4
    - name: Set up GTK environment variables
      run: |
        echo "::set-env name=PKG_CONFIG_PATH::/usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig"
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
    - name: building
      run: |
        cmake --build build --config Debug --target unit_tests -j4
    - name: testing
      run: |
        cd build
        cd bin
        ./unit_tests
