name: MacOS CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Homebrew Update
      run: |
        rm -f /usr/local/bin/2to3*
        rm -f /usr/local/bin/idle*
        rm -f /usr/local/bin/pydoc3*
        rm -f /usr/local/bin/python3*
        brew update --preinstall
    - name: Install GTK
      run: brew install gtk4
        #- name: Set up GTK environment variables
        #run: |
        #echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig" >> "$GITHUB_ENV"
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
    - name: building
      run: |
        cmake --build build --config Debug --target unit_tests -j4
    - name: testing
      run: |
        cd build
        cd bin
        ./unit_tests
