name: pre-commit

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  pre-commit:  
    runs-on: ubuntu-latest    
    steps:
    - name: Install libcap-dev
      run: sudo apt-get install libcap-dev    
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
